### PR TITLE
Implement a strict certifiable OIDC flow

### PR DESCRIPTION
**Pull request by MarcusGrass**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This PR aims to make tame-oidc oidc-relying-party-certifiable which means passing some tests that OIDC has set up https://www.certification.openid.net/

To do this a strict flow was implemented which will ensure compliance if used, while the tools used by it can be used to construct your own possibly compliant flow, but without any guarantees. 

The oidc tests require implementation of basic auth, so that was added. Additionally some JWT verification methods were added. 

Some imperfect implementation details:

- We only try RSA JWKS
- We try all JWKS when trying to verify a signature in no particular order even though we (likely) have the key_id used to sign the token. Simplifies the case where a key_id is omitted, if the provider only provides one set of keys we're supposed to use that, if the provider specifies many it's up to us whether or not to try all or to throw an error, this implementation will try all.

Some improvements I'd like to make when there's more time

- Integration tests, spin up a bare-bones IDP with axum and unit-test so changes aren't so spooky
- Could put different auth methods behind feature gates if we don't want to pull in b64 if you don't use basic auth

### Related Issues

Pre-requisite for completing https://github.com/EmbarkStudios/tame-oidc/issues/14

### CODE REVIEW

**Comment by repi** [comment]
What's the next step for this, did it get forgotten/lost?

**Comment by MarcusGrass** [comment]
> What's the next step for this, did it get forgotten/lost?

Still needs some review, actually missed the linting but that's fixed now. The cargo deny complains about issues that do not as of yet have a known fix and some duplicate deps from dev-dependencies

**Comment by davidpdrsn** [comment]
I've seen this lying around for some time but don't really know how to go about reviewing it. Its quite a big change and I'm not familiar with the OIDC spec 🤷 Not sure what the best way to go about it is. A guided tour maybe?

**Comment by MarcusGrass** [comment]
> I've seen this lying around for some time but don't really know how to go about reviewing it. Its quite a big change and I'm not familiar with the OIDC spec shrug Not sure what the best way to go about it is. A guided tour maybe?

That could be good, It's tested in that it passes the OIDC test-suite so I don't think a lot of knowledge about the specification itself is necessary for reviewing it, but a check on the code soundness/apis etc would be good

**Review by vojd — APPROVED** [review]
@MarcusGrass and I have stepped through the following conformance tests:
`openid connect core basic certification profile relying party tests` and
`openid connect core post basic certification profile relying party tests` 
in the OpenID conformance test suite at https://www.certification.openid.net/.

The implementation provided in this PR performs as expected and passes all tests with throwing a warning on:
`oidcc-client-test-idtoken-sig-none`

This is expected behavior since `tame-oidc` only supports signed tokens at the moment. 

It would however be a nice addition to add support for passing the `oidcc-client-test-idtoken-sig-none` conformance test in upcoming patches.

**Review by davidpdrsn — APPROVED** [review]
Thats good enough for me 😅

**Pull request merged**
